name: Prueba Runner/Secrets.

on: [push]

jobs:
  comparar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comprobación del repositorio
        uses: actions/checkout@v4

      - name: Comparar token de desarrollo
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
        shell: powershell
        run: |
          Write-Host "Comprobando DEV_TOKEN..."
          Write-Host "Valor local: $env:LOCAL_DEV_TOKEN"
          
          if ("${{ secrets.DEV_TOKEN }}" -eq "$env:LOCAL_DEV_TOKEN") {
              Write-Host "¡Los tokens COINCIDEN correctamente!"
              exit 0
          } else {
              Write-Host "Error: Los tokens NO coinciden."
              exit 1
          }